# Change these first
owner: hackclub-community # Your GitHub organization or username, where this repository lives
repo: community-services-status # The name of this repository
user-agent: "status.hackclub.community (repo: https://github.com/hackclub-community/community-services-status; maintainer: https://andreijiroh.dev)"
skipDeleteIssues: true

sites:
  - name: Hack Club Accounts / Auth
    url: https://auth.hackclub.com/.well-known/openid-configuration
    slug: auth
  - name: Community Knot server for Tangled
    url: https://knot.hackclub.community
    slug: tangled-knotserver
    assignees:
    - ajhalili2006

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hackclub.community
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hack Club Community Services Status
  introTitle: "Monitoring uptime for community projects + infra since 2025"
  introMessage: We are monitoring community-run services and projects alongslide Hack Club HQ-sanctioned ones like Accounts/Auth, powered by [Upptime](https://github.com/upptime/upptime). If something is down, the maintainer behind that service will be paged through issue assignments.
  navbar:
    - title: Status
      href: /
    - title: Source repo
      href: https://github.com/$OWNER/$REPO
    - title: Nest status
      href: https://status.hackclub.com

# disable these updates to avoid overrides
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

# tweak commit message template and author metadata
commitMessages:
  commitAuthorName: Hack Club Community Operations Bot
  commitAuthorEmail: 237746918+hackclub-community-ops@users.noreply.github.com

# more tweaking hell
delay: 5000 # 5 seconds
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
